fastlane_require 'dotenv'

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

before_all do |_lane, _options|
  Dotenv.load(".env.#{ENV['ENV']}.secret")
end

default_platform(:ios)

platform :ios do
  desc 'Description of what the lane does'
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
    puts (ENV['ENV']).to_s
    puts (ENV['IOS_APP_ID']).to_s
    puts (ENV['P12_PASSWORD']).to_s
  end
end

platform :android do
  desc 'Build android project'
  lane :build do
    sh 'cd ../;flutter clean; flutter build apk --release;cd fastlane;'
    dist = "#{ENV['ANDROID_OUTPUT_PATH']}/#{ENV['ENV']}/"
    sh "mkdir -p #{dist}"
    sh "cp ../#{ENV['ANDROID_APK_PATH']} #{dist}"
  end
end
